// Realistic-shaped YouTube player fragment used for OFFLINE cross-validation of
// the goja signature/nsig engine against the reference Python yt-dlp JSInterpreter.
//
// It mirrors the *structure* YouTube actually ships today:
//   * the signature transform is a `function(a, b)` (b = sts timestamp) that splits
//     the string into a char array, applies helper-object method calls (reverse /
//     slice / splice), and rejoins — exactly the shape our `findTransform` is built
//     to localize via the `split("")...join("")` marker.
//   * the "n" (throttling) transform is applied in place through a self-reassigning
//     call `n = NAME(n)` — the precise call-site our `findNByCallSite` keys on.
//   * a decoy n-shaped function exists but is never self-called, so the call-site
//     locator must ignore it (proves precision, not just shape-matching).
//
// The expected deobfuscated outputs for a fixed set of inputs live in
// realistic_player.expected.json, generated by scripts/crosscheck.py from the
// reference interpreter. The Go test asserts our goja engine reproduces them byte
// for byte.

var _yt_player = {};

var PLAYER_h={reverse:function(a){return a.reverse()},slice:function(a,b){return a.slice(b)},splice:function(a,b){a.splice(0,b);return a}};

// A decoy n-shaped function: it is n-shaped (uses .slice + returns) but is NEVER
// self-called, so findNByCallSite must NOT select it.
function PLAYER_decoy(a) { a = a.slice(1); return a; }

// The real "n" throttling transform, applied in place via a self-call below.
function PLAYER_nsig(a) {
  a = a.slice(2);
  var b = a.length;
  a = a.slice(b % 3);
  return a;
}

// The signature transform. Receives the sts timestamp as the second argument `b`
// (modern YouTube form) and uses it in a slice index.
function PLAYER_sig(a, b) {
  a = a.split("");
  PLAYER_h.reverse(a);
  a = PLAYER_h.slice(a, b % a.length);
  PLAYER_h.splice(a, 1);
  return a.join("");
}

// Elsewhere the player applies the n-transform in place. This is the signal
// findNByCallSite keys on: `n = PLAYER_nsig(n)`.
var n = "";
n = PLAYER_nsig(n);

// A self-call of a non-n-shaped function: must be ignored by the n locator.
var t = 0;
t = PLAYER_identity(t);
function PLAYER_identity(a) { return a; }
